### ISSUE TITLE
Feature Enhancement: provide logic to replace cached auth token if it fails with active user github auth token.

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#355]
Currently, based on the issue we had trying to recompile wavefront handler.. it appears that its possible for the cached github token that is part of an asset extensions data can become stale, and we need a way to refresh the cached authentication token.

## My current understanding
When we create an asset for the first time the github access token used at the time of asset creation is cached as part of the asset's database record model used in bonsai.   If for some reason this access token becomes invalid later, this will prevent bonsai from accessing the github api to pull repository information even for public repos.

We need a way to refresh this cached access token, replacing the failing cached token with the access token from the active user using bonsai's website.

## Straw proposal
Cache an extension’s most recent working GitHub auth token. The starting value is the extension owner’s auth token, determined when the asset is first added to bonsai. If this cached token stops working, try the current user’s token.

**Comment by jspaleta** [comment]
Related to the issue #353

**Comment by jspaleta** [comment]
Current example on staging:
https://bonsai-asset-index-staging.herokuapp.com/assets/sensu/sensu-email-handler

When i attempt to recompile I get this banner:
```
Retrying Compilations: ExtractExtensionParentWorker, SyncExtensionRepoWorker
Compiling Extension % 0.0 Complete
```

**Comment by jspaleta** [comment]
log line from papertrail

```
2022-03-16T20:39:28.000Z bonsai-asset-index-staging app/worker.1 4 TID-ouhhvur6c WARN: {"context":"Job raised exception","job":{"class":"SyncExtensionRepoWorker","args":[7],"retry":true,"queue":"default","backtrace":true,"jid":"bc89631cfb8d106084c45322","created_at":1647462521.499293,"enqueued_at":1647463167.7811065,"error_message":"GET https://api.github.com/repos/sensu/sensu-email-handler/releases: 401 - Bad credentials // See: https://docs.github.com/rest","error_class":"Octokit::Unauthorized","failed_at":1647462521.7606618,"retry_count":4,"error_backtrace":["/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/response/raise_error.rb:14:in `on_complete'","/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'","/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'","/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'","/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/request/retry.rb:128:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'","/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'","/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'","/app/vendor/bundle/ruby/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/connection.rb:156:in `request'","/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/connection.rb:84:in `paginate'","/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/client/releases.rb:15:in `releases'","/app/app/workers/sync_extension_repo_worker.rb:6:in `perform'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-status-1.1.4/lib/sidekiq-status/server_middleware.rb:50:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/app/vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.1/lib/airbrake/sidekiq.rb:11:in `block in call'","/app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.13.0/lib/airbrake-ruby/benchmark.rb:13:in `measure'","/app/vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.1/lib/airbrake/sidekiq.rb:10:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'","/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'","/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:73:in `block in wrap'","/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'","/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'","/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'"],"retried_at":1647462813.1914077},"jobstr":"{\"class\":\"SyncExtensionRepoWorker\",\"args\":[7],\"retry\":true,\"queue\":\"default\",\"backtrace\":true,\"jid\":\"bc89631cfb8d106084c45322\",\"created_at\":1647462521.499293,\"enqueued_at\":1647463167.7811065,\"error_message\":\"GET https://api.github.com/repos/sensu/sensu-email-handler/releases: 401 - Bad credentials // See: https://docs.github.com/rest\",\"error_class\":\"Octokit::Unauthorized\",\"failed_at\":1647462521.7606618,\"retry_count\":4,\"error_backtrace\":[\"/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/response/raise_error.rb:14:in `on_complete'\",\"/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'\",\"/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'\",\"/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/request/retry.rb:128:in `call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'\",\"/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'\",\"/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/connection.rb:156:in `request'\",\"/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/connection.rb:84:in `paginate'\",\"/app/vendor/bundle/ruby/2.5.0/gems/octokit-4.21.0/lib/octokit/client/releases.rb:15:in `releases'\",\"/app/app/workers/sync_extension_repo_worker.rb:6:in `perform'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-status-1.1.4/lib/sidekiq-status/server_middleware.rb:50:in `call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/app/vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.1/lib/airbrake/sidekiq.rb:11:in `block in call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-4.13.0/lib/airbrake-ruby/benchmark.rb:13:in `measure'\",\"/app/vendor/bundle/ruby/2.5.0/gems/airbrake-10.0.1/lib/airbrake/sidekiq.rb:10:in `call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'\",\"/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:73:in `block in wrap'\",\"/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'\",\"/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'\",\"/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_

```
